generatorName: go
inputSpec: openapi.json
gitHost: immutable.com
gitUserId: ""
gitRepoId: imx-core-sdk-golang
enablePostProcessFile: true
additionalProperties:
  enumClassPrefix: "true"
  packageName: api
  packageVersion: 0.1.0
  generateInterfaces: true
  isGoSubmodule: true