generatorName: go
inputSpec: openapi.json
gitHost: github.com
gitUserId: immutable
gitRepoId: imx-core-sdk-golang
enablePostProcessFile: true
additionalProperties:
  enumClassPrefix: "true"
  packageName: api
  packageVersion: 1.0.0-beta   # Todo: Auto generate this version string from the release git tags.
  generateInterfaces: true
  isGoSubmodule: true