/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetSignableOrderResponseFeeInfo Fee information
type GetSignableOrderResponseFeeInfo struct {
	// ID of the asset these fees relate to
	AssetId string `json:"asset_id"`
	// Fee limit
	FeeLimit string `json:"fee_limit"`
	// ID of vault the asset belong to
	SourceVaultId int32 `json:"source_vault_id"`
}

// NewGetSignableOrderResponseFeeInfo instantiates a new GetSignableOrderResponseFeeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSignableOrderResponseFeeInfo(assetId string, feeLimit string, sourceVaultId int32) *GetSignableOrderResponseFeeInfo {
	this := GetSignableOrderResponseFeeInfo{}
	this.AssetId = assetId
	this.FeeLimit = feeLimit
	this.SourceVaultId = sourceVaultId
	return &this
}

// NewGetSignableOrderResponseFeeInfoWithDefaults instantiates a new GetSignableOrderResponseFeeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSignableOrderResponseFeeInfoWithDefaults() *GetSignableOrderResponseFeeInfo {
	this := GetSignableOrderResponseFeeInfo{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *GetSignableOrderResponseFeeInfo) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *GetSignableOrderResponseFeeInfo) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *GetSignableOrderResponseFeeInfo) SetAssetId(v string) {
	o.AssetId = v
}

// GetFeeLimit returns the FeeLimit field value
func (o *GetSignableOrderResponseFeeInfo) GetFeeLimit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeLimit
}

// GetFeeLimitOk returns a tuple with the FeeLimit field value
// and a boolean to check if the value has been set.
func (o *GetSignableOrderResponseFeeInfo) GetFeeLimitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeLimit, true
}

// SetFeeLimit sets field value
func (o *GetSignableOrderResponseFeeInfo) SetFeeLimit(v string) {
	o.FeeLimit = v
}

// GetSourceVaultId returns the SourceVaultId field value
func (o *GetSignableOrderResponseFeeInfo) GetSourceVaultId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SourceVaultId
}

// GetSourceVaultIdOk returns a tuple with the SourceVaultId field value
// and a boolean to check if the value has been set.
func (o *GetSignableOrderResponseFeeInfo) GetSourceVaultIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceVaultId, true
}

// SetSourceVaultId sets field value
func (o *GetSignableOrderResponseFeeInfo) SetSourceVaultId(v int32) {
	o.SourceVaultId = v
}

func (o GetSignableOrderResponseFeeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset_id"] = o.AssetId
	}
	if true {
		toSerialize["fee_limit"] = o.FeeLimit
	}
	if true {
		toSerialize["source_vault_id"] = o.SourceVaultId
	}
	return json.Marshal(toSerialize)
}

type NullableGetSignableOrderResponseFeeInfo struct {
	value *GetSignableOrderResponseFeeInfo
	isSet bool
}

func (v NullableGetSignableOrderResponseFeeInfo) Get() *GetSignableOrderResponseFeeInfo {
	return v.value
}

func (v *NullableGetSignableOrderResponseFeeInfo) Set(val *GetSignableOrderResponseFeeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSignableOrderResponseFeeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSignableOrderResponseFeeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSignableOrderResponseFeeInfo(val *GetSignableOrderResponseFeeInfo) *NullableGetSignableOrderResponseFeeInfo {
	return &NullableGetSignableOrderResponseFeeInfo{value: val, isSet: true}
}

func (v NullableGetSignableOrderResponseFeeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSignableOrderResponseFeeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


