/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateOrderResponse struct for CreateOrderResponse
type CreateOrderResponse struct {
	// ID of the created order
	OrderId int32 `json:"order_id"`
	// Request ID as a reference for an asynchronous order creation request
	RequestId *string `json:"request_id,omitempty"`
	// Status of the created order
	Status string `json:"status"`
	// Timestamp of the created order
	Time int32 `json:"time"`
}

// NewCreateOrderResponse instantiates a new CreateOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderResponse(orderId int32, status string, time int32) *CreateOrderResponse {
	this := CreateOrderResponse{}
	this.OrderId = orderId
	this.Status = status
	this.Time = time
	return &this
}

// NewCreateOrderResponseWithDefaults instantiates a new CreateOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderResponseWithDefaults() *CreateOrderResponse {
	this := CreateOrderResponse{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *CreateOrderResponse) GetOrderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CreateOrderResponse) GetOrderIdOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CreateOrderResponse) SetOrderId(v int32) {
	o.OrderId = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreateOrderResponse) GetRequestId() string {
	if o == nil || isNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || isNil(o.RequestId) {
    return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateOrderResponse) HasRequestId() bool {
	if o != nil && !isNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreateOrderResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetStatus returns the Status field value
func (o *CreateOrderResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateOrderResponse) GetStatusOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateOrderResponse) SetStatus(v string) {
	o.Status = v
}

// GetTime returns the Time field value
func (o *CreateOrderResponse) GetTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *CreateOrderResponse) GetTimeOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *CreateOrderResponse) SetTime(v int32) {
	o.Time = v
}

func (o CreateOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["order_id"] = o.OrderId
	}
	if !isNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["time"] = o.Time
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderResponse struct {
	value *CreateOrderResponse
	isSet bool
}

func (v NullableCreateOrderResponse) Get() *CreateOrderResponse {
	return v.value
}

func (v *NullableCreateOrderResponse) Set(val *CreateOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderResponse(val *CreateOrderResponse) *NullableCreateOrderResponse {
	return &NullableCreateOrderResponse{value: val, isSet: true}
}

func (v NullableCreateOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


