/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the FeeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeeData{}

// FeeData struct for FeeData
type FeeData struct {
	// Address of ERC721/ERC20 contract
	ContractAddress *string `json:"contract_address,omitempty"`
	// Number of decimals supported by this asset
	Decimals *int32 `json:"decimals,omitempty"`
}

// NewFeeData instantiates a new FeeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeeData() *FeeData {
	this := FeeData{}
	return &this
}

// NewFeeDataWithDefaults instantiates a new FeeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeeDataWithDefaults() *FeeData {
	this := FeeData{}
	return &this
}

// GetContractAddress returns the ContractAddress field value if set, zero value otherwise.
func (o *FeeData) GetContractAddress() string {
	if o == nil || isNil(o.ContractAddress) {
		var ret string
		return ret
	}
	return *o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeData) GetContractAddressOk() (*string, bool) {
	if o == nil || isNil(o.ContractAddress) {
		return nil, false
	}
	return o.ContractAddress, true
}

// HasContractAddress returns a boolean if a field has been set.
func (o *FeeData) HasContractAddress() bool {
	if o != nil && !isNil(o.ContractAddress) {
		return true
	}

	return false
}

// SetContractAddress gets a reference to the given string and assigns it to the ContractAddress field.
func (o *FeeData) SetContractAddress(v string) {
	o.ContractAddress = &v
}

// GetDecimals returns the Decimals field value if set, zero value otherwise.
func (o *FeeData) GetDecimals() int32 {
	if o == nil || isNil(o.Decimals) {
		var ret int32
		return ret
	}
	return *o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeeData) GetDecimalsOk() (*int32, bool) {
	if o == nil || isNil(o.Decimals) {
		return nil, false
	}
	return o.Decimals, true
}

// HasDecimals returns a boolean if a field has been set.
func (o *FeeData) HasDecimals() bool {
	if o != nil && !isNil(o.Decimals) {
		return true
	}

	return false
}

// SetDecimals gets a reference to the given int32 and assigns it to the Decimals field.
func (o *FeeData) SetDecimals(v int32) {
	o.Decimals = &v
}

func (o FeeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ContractAddress) {
		toSerialize["contract_address"] = o.ContractAddress
	}
	if !isNil(o.Decimals) {
		toSerialize["decimals"] = o.Decimals
	}
	return toSerialize, nil
}

type NullableFeeData struct {
	value *FeeData
	isSet bool
}

func (v NullableFeeData) Get() *FeeData {
	return v.value
}

func (v *NullableFeeData) Set(val *FeeData) {
	v.value = val
	v.isSet = true
}

func (v NullableFeeData) IsSet() bool {
	return v.isSet
}

func (v *NullableFeeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeeData(val *FeeData) *NullableFeeData {
	return &NullableFeeData{value: val, isSet: true}
}

func (v NullableFeeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


