/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetSignableCancelOrderResponse struct for GetSignableCancelOrderResponse
type GetSignableCancelOrderResponse struct {
	// ID of the order to be cancelled
	OrderId int32 `json:"order_id"`
	// Hash of the payload to be signed for cancel order
	PayloadHash string `json:"payload_hash"`
	// Message to sign from wallet to confirm cancel order
	SignableMessage string `json:"signable_message"`
}

// NewGetSignableCancelOrderResponse instantiates a new GetSignableCancelOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSignableCancelOrderResponse(orderId int32, payloadHash string, signableMessage string) *GetSignableCancelOrderResponse {
	this := GetSignableCancelOrderResponse{}
	this.OrderId = orderId
	this.PayloadHash = payloadHash
	this.SignableMessage = signableMessage
	return &this
}

// NewGetSignableCancelOrderResponseWithDefaults instantiates a new GetSignableCancelOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSignableCancelOrderResponseWithDefaults() *GetSignableCancelOrderResponse {
	this := GetSignableCancelOrderResponse{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *GetSignableCancelOrderResponse) GetOrderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *GetSignableCancelOrderResponse) GetOrderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *GetSignableCancelOrderResponse) SetOrderId(v int32) {
	o.OrderId = v
}

// GetPayloadHash returns the PayloadHash field value
func (o *GetSignableCancelOrderResponse) GetPayloadHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PayloadHash
}

// GetPayloadHashOk returns a tuple with the PayloadHash field value
// and a boolean to check if the value has been set.
func (o *GetSignableCancelOrderResponse) GetPayloadHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayloadHash, true
}

// SetPayloadHash sets field value
func (o *GetSignableCancelOrderResponse) SetPayloadHash(v string) {
	o.PayloadHash = v
}

// GetSignableMessage returns the SignableMessage field value
func (o *GetSignableCancelOrderResponse) GetSignableMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignableMessage
}

// GetSignableMessageOk returns a tuple with the SignableMessage field value
// and a boolean to check if the value has been set.
func (o *GetSignableCancelOrderResponse) GetSignableMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignableMessage, true
}

// SetSignableMessage sets field value
func (o *GetSignableCancelOrderResponse) SetSignableMessage(v string) {
	o.SignableMessage = v
}

func (o GetSignableCancelOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["order_id"] = o.OrderId
	}
	if true {
		toSerialize["payload_hash"] = o.PayloadHash
	}
	if true {
		toSerialize["signable_message"] = o.SignableMessage
	}
	return json.Marshal(toSerialize)
}

type NullableGetSignableCancelOrderResponse struct {
	value *GetSignableCancelOrderResponse
	isSet bool
}

func (v NullableGetSignableCancelOrderResponse) Get() *GetSignableCancelOrderResponse {
	return v.value
}

func (v *NullableGetSignableCancelOrderResponse) Set(val *GetSignableCancelOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSignableCancelOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSignableCancelOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSignableCancelOrderResponse(val *GetSignableCancelOrderResponse) *NullableGetSignableCancelOrderResponse {
	return &NullableGetSignableCancelOrderResponse{value: val, isSet: true}
}

func (v NullableGetSignableCancelOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSignableCancelOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


