/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// GetSignableTradeResponseFeeInfo Fee information
type GetSignableTradeResponseFeeInfo struct {
	// ID of the asset these fees relate to
	AssetId string `json:"asset_id"`
	// Fee limit
	FeeLimit string `json:"fee_limit"`
	// ID of vault the asset belong to
	SourceVaultId int32 `json:"source_vault_id"`
}

// NewGetSignableTradeResponseFeeInfo instantiates a new GetSignableTradeResponseFeeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSignableTradeResponseFeeInfo(assetId string, feeLimit string, sourceVaultId int32) *GetSignableTradeResponseFeeInfo {
	this := GetSignableTradeResponseFeeInfo{}
	this.AssetId = assetId
	this.FeeLimit = feeLimit
	this.SourceVaultId = sourceVaultId
	return &this
}

// NewGetSignableTradeResponseFeeInfoWithDefaults instantiates a new GetSignableTradeResponseFeeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSignableTradeResponseFeeInfoWithDefaults() *GetSignableTradeResponseFeeInfo {
	this := GetSignableTradeResponseFeeInfo{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *GetSignableTradeResponseFeeInfo) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *GetSignableTradeResponseFeeInfo) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *GetSignableTradeResponseFeeInfo) SetAssetId(v string) {
	o.AssetId = v
}

// GetFeeLimit returns the FeeLimit field value
func (o *GetSignableTradeResponseFeeInfo) GetFeeLimit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeLimit
}

// GetFeeLimitOk returns a tuple with the FeeLimit field value
// and a boolean to check if the value has been set.
func (o *GetSignableTradeResponseFeeInfo) GetFeeLimitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeLimit, true
}

// SetFeeLimit sets field value
func (o *GetSignableTradeResponseFeeInfo) SetFeeLimit(v string) {
	o.FeeLimit = v
}

// GetSourceVaultId returns the SourceVaultId field value
func (o *GetSignableTradeResponseFeeInfo) GetSourceVaultId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SourceVaultId
}

// GetSourceVaultIdOk returns a tuple with the SourceVaultId field value
// and a boolean to check if the value has been set.
func (o *GetSignableTradeResponseFeeInfo) GetSourceVaultIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceVaultId, true
}

// SetSourceVaultId sets field value
func (o *GetSignableTradeResponseFeeInfo) SetSourceVaultId(v int32) {
	o.SourceVaultId = v
}

func (o GetSignableTradeResponseFeeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset_id"] = o.AssetId
	}
	if true {
		toSerialize["fee_limit"] = o.FeeLimit
	}
	if true {
		toSerialize["source_vault_id"] = o.SourceVaultId
	}
	return json.Marshal(toSerialize)
}

type NullableGetSignableTradeResponseFeeInfo struct {
	value *GetSignableTradeResponseFeeInfo
	isSet bool
}

func (v NullableGetSignableTradeResponseFeeInfo) Get() *GetSignableTradeResponseFeeInfo {
	return v.value
}

func (v *NullableGetSignableTradeResponseFeeInfo) Set(val *GetSignableTradeResponseFeeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSignableTradeResponseFeeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSignableTradeResponseFeeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSignableTradeResponseFeeInfo(val *GetSignableTradeResponseFeeInfo) *NullableGetSignableTradeResponseFeeInfo {
	return &NullableGetSignableTradeResponseFeeInfo{value: val, isSet: true}
}

func (v NullableGetSignableTradeResponseFeeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSignableTradeResponseFeeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


