/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ListTokensResponse struct for ListTokensResponse
type ListTokensResponse struct {
	// Generated cursor returned by previous query
	Cursor string `json:"cursor"`
	// Tokens matching query parameters
	Result []TokenDetails `json:"result"`
}

// NewListTokensResponse instantiates a new ListTokensResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTokensResponse(cursor string, result []TokenDetails) *ListTokensResponse {
	this := ListTokensResponse{}
	this.Cursor = cursor
	this.Result = result
	return &this
}

// NewListTokensResponseWithDefaults instantiates a new ListTokensResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTokensResponseWithDefaults() *ListTokensResponse {
	this := ListTokensResponse{}
	return &this
}

// GetCursor returns the Cursor field value
func (o *ListTokensResponse) GetCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *ListTokensResponse) GetCursorOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *ListTokensResponse) SetCursor(v string) {
	o.Cursor = v
}

// GetResult returns the Result field value
func (o *ListTokensResponse) GetResult() []TokenDetails {
	if o == nil {
		var ret []TokenDetails
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ListTokensResponse) GetResultOk() ([]TokenDetails, bool) {
	if o == nil {
    return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *ListTokensResponse) SetResult(v []TokenDetails) {
	o.Result = v
}

func (o ListTokensResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cursor"] = o.Cursor
	}
	if true {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableListTokensResponse struct {
	value *ListTokensResponse
	isSet bool
}

func (v NullableListTokensResponse) Get() *ListTokensResponse {
	return v.value
}

func (v *NullableListTokensResponse) Set(val *ListTokensResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTokensResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTokensResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTokensResponse(val *ListTokensResponse) *NullableListTokensResponse {
	return &NullableListTokensResponse{value: val, isSet: true}
}

func (v NullableListTokensResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTokensResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


