/*
Immutable X API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
Contact: support@immutable.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// EncodeAssetRequestTokenData Extra token information to be encoded
type EncodeAssetRequestTokenData struct {
	// Blueprint information of the token to be encoded. Used if token is mintable.
	Blueprint *string `json:"blueprint,omitempty"`
	// ID of the token to be encoded. Used if token is mintable.
	Id *string `json:"id,omitempty"`
	// Contract address of the token to be encoded
	TokenAddress *string `json:"token_address,omitempty"`
	// TokenId of the token to be encoded. Used if token is non-mintable
	TokenId *string `json:"token_id,omitempty"`
}

// NewEncodeAssetRequestTokenData instantiates a new EncodeAssetRequestTokenData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEncodeAssetRequestTokenData() *EncodeAssetRequestTokenData {
	this := EncodeAssetRequestTokenData{}
	return &this
}

// NewEncodeAssetRequestTokenDataWithDefaults instantiates a new EncodeAssetRequestTokenData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEncodeAssetRequestTokenDataWithDefaults() *EncodeAssetRequestTokenData {
	this := EncodeAssetRequestTokenData{}
	return &this
}

// GetBlueprint returns the Blueprint field value if set, zero value otherwise.
func (o *EncodeAssetRequestTokenData) GetBlueprint() string {
	if o == nil || o.Blueprint == nil {
		var ret string
		return ret
	}
	return *o.Blueprint
}

// GetBlueprintOk returns a tuple with the Blueprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeAssetRequestTokenData) GetBlueprintOk() (*string, bool) {
	if o == nil || o.Blueprint == nil {
		return nil, false
	}
	return o.Blueprint, true
}

// HasBlueprint returns a boolean if a field has been set.
func (o *EncodeAssetRequestTokenData) HasBlueprint() bool {
	if o != nil && o.Blueprint != nil {
		return true
	}

	return false
}

// SetBlueprint gets a reference to the given string and assigns it to the Blueprint field.
func (o *EncodeAssetRequestTokenData) SetBlueprint(v string) {
	o.Blueprint = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EncodeAssetRequestTokenData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeAssetRequestTokenData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EncodeAssetRequestTokenData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EncodeAssetRequestTokenData) SetId(v string) {
	o.Id = &v
}

// GetTokenAddress returns the TokenAddress field value if set, zero value otherwise.
func (o *EncodeAssetRequestTokenData) GetTokenAddress() string {
	if o == nil || o.TokenAddress == nil {
		var ret string
		return ret
	}
	return *o.TokenAddress
}

// GetTokenAddressOk returns a tuple with the TokenAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeAssetRequestTokenData) GetTokenAddressOk() (*string, bool) {
	if o == nil || o.TokenAddress == nil {
		return nil, false
	}
	return o.TokenAddress, true
}

// HasTokenAddress returns a boolean if a field has been set.
func (o *EncodeAssetRequestTokenData) HasTokenAddress() bool {
	if o != nil && o.TokenAddress != nil {
		return true
	}

	return false
}

// SetTokenAddress gets a reference to the given string and assigns it to the TokenAddress field.
func (o *EncodeAssetRequestTokenData) SetTokenAddress(v string) {
	o.TokenAddress = &v
}

// GetTokenId returns the TokenId field value if set, zero value otherwise.
func (o *EncodeAssetRequestTokenData) GetTokenId() string {
	if o == nil || o.TokenId == nil {
		var ret string
		return ret
	}
	return *o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeAssetRequestTokenData) GetTokenIdOk() (*string, bool) {
	if o == nil || o.TokenId == nil {
		return nil, false
	}
	return o.TokenId, true
}

// HasTokenId returns a boolean if a field has been set.
func (o *EncodeAssetRequestTokenData) HasTokenId() bool {
	if o != nil && o.TokenId != nil {
		return true
	}

	return false
}

// SetTokenId gets a reference to the given string and assigns it to the TokenId field.
func (o *EncodeAssetRequestTokenData) SetTokenId(v string) {
	o.TokenId = &v
}

func (o EncodeAssetRequestTokenData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Blueprint != nil {
		toSerialize["blueprint"] = o.Blueprint
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.TokenAddress != nil {
		toSerialize["token_address"] = o.TokenAddress
	}
	if o.TokenId != nil {
		toSerialize["token_id"] = o.TokenId
	}
	return json.Marshal(toSerialize)
}

type NullableEncodeAssetRequestTokenData struct {
	value *EncodeAssetRequestTokenData
	isSet bool
}

func (v NullableEncodeAssetRequestTokenData) Get() *EncodeAssetRequestTokenData {
	return v.value
}

func (v *NullableEncodeAssetRequestTokenData) Set(val *EncodeAssetRequestTokenData) {
	v.value = val
	v.isSet = true
}

func (v NullableEncodeAssetRequestTokenData) IsSet() bool {
	return v.isSet
}

func (v *NullableEncodeAssetRequestTokenData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncodeAssetRequestTokenData(val *EncodeAssetRequestTokenData) *NullableEncodeAssetRequestTokenData {
	return &NullableEncodeAssetRequestTokenData{value: val, isSet: true}
}

func (v NullableEncodeAssetRequestTokenData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncodeAssetRequestTokenData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


