/*
Immutable X API

Testing EncodingApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/immutable/imx-core-sdk-golang/api"
)

func Test_api_EncodingApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EncodingApiService EncodeAsset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetType string

		resp, httpRes, err := apiClient.EncodingApi.EncodeAsset(context.Background(), assetType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
