/*
Immutable X API

Testing MetadataApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/immutable/imx-core-sdk-golang/api"
)

func Test_api_MetadataApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MetadataApiService AddMetadataSchemaToCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string

		resp, httpRes, err := apiClient.MetadataApi.AddMetadataSchemaToCollection(context.Background(), address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataApiService GetMetadataSchema", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string

		resp, httpRes, err := apiClient.MetadataApi.GetMetadataSchema(context.Background(), address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MetadataApiService UpdateMetadataSchemaByName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string
		var name string

		resp, httpRes, err := apiClient.MetadataApi.UpdateMetadataSchemaByName(context.Background(), address, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
