name: Leaked Secrets Scan
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "trufflehog:3.4.3"
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

