name: Leaked Secrets Scan
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: docker://ghcr.io/trufflesecurity/trufflehog:3.6.9
        with:
          # Here is the meaning for the following args
          # "git" "file://./"                                                 # Repository path
          # "--since-commit" "${{ github.event.repository.default_branch }}"  # Start scanning from here (usually main branch).
          # "--branch" HEAD                                                   # Scan commits until here (usually dev branch).
          # --fail                                                            # On finding issues fails with a error code
          args: |
            "git" "file://./" "--since-commit" "${{ github.event.repository.default_branch }}" "--branch" "HEAD" "--fail"
