name: Leaked Secrets Scan
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: docker://ghcr.io/trufflesecurity/trufflehog:3.6.9
        with:
          args: |
            "git" "file://./" "--since-commit" "${{ github.event.repository.default_branch }}" "--branch" "HEAD" "--fail"
